Задача 2
ivankrn/WeatherForecastBotOopCourse pull request #17
Opened 2023-12-06 04:10 UTC by ivankrn

Теперь с ботом можно взаимодействовать в форме диалога. Например, если раньше требовалось в команде прогноза сразу указывать город и временной период (пример: /info_week Екатеринбург), то теперь можно запросить прогноз без параметров, а бот сам уточнит недостающие детали у пользователя (например, если ввести просто /info_week, то бот запросит место для прогноза на неделю). Также добавлены кнопки для упрощения взаимодействия с ботом (например, если нажать кнопку "узнать прогноз", бот последовательно уточнит в каком месте и на какой временной период нужно прислать прогноз).

2023-12-07 15:27 UTC, vpyzhyanov requested changes
1. Добро пожаловать на тёмную сторону ООП, вы перегрузили класс функционалом. Он уже плачет от нагрузки.
2. Нет тестов на переход между состояниями
3. Зря вы выбрали недетерминированный автомат, это очень сильно усложняет логику программы и увеличивает сложность добавления новых команд и состояний. А ещё нет никакого контроля за состояниями. В моём идеальном мире надо использовать детерминированный автомат с указанием возможных переходов и обработчиков для каждого состояния. Это делает более сложной реализацию автомата, но зато программа становится существенно проще и понятнее. И очень легко разделить логику обработки команд и состояний.

![image](https://github.com/ivankrn/WeatherForecastBotOopCourse/assets/71599019/bc44867f-7272-4c6c-a2bb-e794fa3b464d)

2023-12-07 15:27 UTC, vpyzhyanov commented on src/test/java/ru/urfu/weatherforecastbot/bot/MessageHandlerImplTest.java
>      @Mock
![image](https://github.com/ivankrn/WeatherForecastBotOopCourse/assets/71599019/cfdf24f1-300c-4544-9571-27d78c458b98)

Это не сервис, а просто класс, его не нужно мокать, чтобы в тесте **не дублировать логику форматирования**.

2023-12-07 15:27 UTC, vpyzhyanov commented on src/test/java/ru/urfu/weatherforecastbot/bot/MessageHandlerImplTest.java
> +                .thenReturn("Прогноз погоды на сегодня (Екатеринбург): ...");
дублирование логики. Это просто класс, это не бин и не сервис, его не нужно мокать. Точнее нет в этом никакого смысла.

2023-12-07 15:27 UTC, vpyzhyanov commented on src/test/java/ru/urfu/weatherforecastbot/bot/MessageHandlerImplTest.java
> +        when(chatStateRepository.findById(chatId)).thenReturn(Optional.of(chatState));
во всём классе нет ни одной проверки, что состояние изменилось на правильное!!! Отсюда я делаю вывод, что нет ни одного теста на Задачу 2.

2023-12-07 15:27 UTC, vpyzhyanov commented on src/test/java/ru/urfu/weatherforecastbot/bot/MessageHandlerImplTest.java
> +        return messageMarkup.getKeyboard().stream()
вот ещё один пример неудобства написания тестов из-за плохой архитектуры (связи телеграмм бота и обработчика сообщений). Иначе бы не пришлось делать такие методы.

2023-12-07 15:27 UTC, vpyzhyanov commented on src/test/java/ru/urfu/weatherforecastbot/bot/MessageHandlerImplTest.java
> +     * @return список кнопок, прикрепленных к сообщению
вот вам не лень 2 раза писать одно и то же

2023-12-07 15:27 UTC, vpyzhyanov commented on src/test/java/ru/urfu/weatherforecastbot/bot/MessageHandlerImplTest.java
> +        assertTrue(forecastWeekResponseButtons.stream().anyMatch(button -> button.getText().equals("Отмена")));
плохая проверка. Тут могут быть любые кнопки, и тест это никак не контролирует. Нужно проверять на equals

2023-12-07 15:27 UTC, vpyzhyanov commented on src/test/java/ru/urfu/weatherforecastbot/bot/MessageHandlerImplTest.java
> +        assertTrue(responseMessageButtons.stream().anyMatch(button -> button.getText().equals("Узнать прогноз")));
плохие проверки. В других тестах то же самое

Вам правда плевать на то в каком порядке они будут?

2023-12-13 15:20 UTC, ivankrn commented on pom.xml
> +			<artifactId>h2</artifactId>
Исправил

2023-12-13 15:20 UTC, ivankrn commented on src/main/java/ru/urfu/weatherforecastbot/bot/MessageHandlerImpl.java
> +                case BotConstants.COMMAND_START -> {
Исправил

2023-12-13 15:20 UTC, ivankrn commented on src/main/java/ru/urfu/weatherforecastbot/bot/MessageHandlerImpl.java
> +        switch (currentBotState) {
Исправил

2023-12-13 15:20 UTC, ivankrn commented on src/main/java/ru/urfu/weatherforecastbot/bot/MessageHandlerImpl.java
> +     * @return встроенная разметка клавиатуры для главного меню
Исправил

2023-12-13 15:21 UTC, ivankrn commented on src/main/java/ru/urfu/weatherforecastbot/bot/MessageHandlerImpl.java
> +    private InlineKeyboardMarkup getCancelReplyMarkup() {
Исправил

2023-12-13 15:21 UTC, ivankrn commented on src/main/java/ru/urfu/weatherforecastbot/bot/MessageHandlerImpl.java
> +    private InlineKeyboardMarkup getTimePeriodMenuReplyMarkup() {
Тоже исправил

2023-12-13 15:21 UTC, ivankrn commented on src/main/java/ru/urfu/weatherforecastbot/model/ChatState.java
> +        return chatId == chatState.chatId && Objects.equals(placeName, chatState.placeName) && botState == chatState.botState;
Исправил (теперь сравнивается по chatId)

2023-12-13 15:21 UTC, ivankrn commented on src/test/java/ru/urfu/weatherforecastbot/bot/MessageHandlerImplTest.java
> +    private ChatStateRepository chatStateRepository;
Исправил

2023-12-13 15:21 UTC, ivankrn commented on src/main/java/ru/urfu/weatherforecastbot/bot/MessageHandlerImpl.java
>          SendMessage responseMessage = new SendMessage();
Исправил

2023-12-13 15:22 UTC, ivankrn commented on src/test/java/ru/urfu/weatherforecastbot/bot/MessageHandlerImplTest.java
>      void whenUserSendsMessage_thenSendMessageToThatUser() {
Исправил

2023-12-13 15:22 UTC, ivankrn commented on src/test/java/ru/urfu/weatherforecastbot/bot/MessageHandlerImplTest.java
>      private WeatherForecastService weatherService;
Исправил

2023-12-13 15:22 UTC, ivankrn commented on src/test/java/ru/urfu/weatherforecastbot/bot/MessageHandlerImplTest.java
>      @Mock
Исправил

2023-12-13 15:22 UTC, ivankrn commented on src/test/java/ru/urfu/weatherforecastbot/bot/MessageHandlerImplTest.java
> +                .thenReturn("Прогноз погоды на сегодня (Екатеринбург): ...");
Исправил

2023-12-13 15:23 UTC, ivankrn commented on src/test/java/ru/urfu/weatherforecastbot/bot/MessageHandlerImplTest.java
> +        when(chatStateRepository.findById(chatId)).thenReturn(Optional.of(chatState));
Исправил

2023-12-13 15:23 UTC, ivankrn commented on src/test/java/ru/urfu/weatherforecastbot/bot/MessageHandlerImplTest.java
> +        return messageMarkup.getKeyboard().stream()
Исправил

2023-12-13 15:23 UTC, ivankrn commented on src/test/java/ru/urfu/weatherforecastbot/bot/MessageHandlerImplTest.java
> +        assertTrue(forecastWeekResponseButtons.stream().anyMatch(button -> button.getText().equals("Отмена")));
Исправил

2023-12-13 15:23 UTC, ivankrn commented on src/test/java/ru/urfu/weatherforecastbot/bot/MessageHandlerImplTest.java
> +        assertTrue(responseMessageButtons.stream().anyMatch(button -> button.getText().equals("Узнать прогноз")));
Исправил (теперь проверяю на equals)

2023-12-13 18:33 UTC, vpyzhyanov commented on src/main/java/ru/urfu/weatherforecastbot/util/WeatherForecastFormatterImpl.java
> +    public String formatTomorrowForecast(List<WeatherForecast> forecasts) throws IllegalArgumentException {
Почему нет ответа на мой вопрос? Я же отвечаю на ваши вопросы, прошу отвечать на мои!

2023-12-13 19:01 UTC, vpyzhyanov requested changes
хорошо, можете мёрджить

2023-12-14 03:14 UTC, ivankrn commented on src/main/java/ru/urfu/weatherforecastbot/util/WeatherForecastFormatterImpl.java
> +    public String formatTomorrowForecast(List<WeatherForecast> forecasts) throws IllegalArgumentException {
Вячеслав Юрьевич, мы когда с Мишей показывали 2 задачу в зуме, вы мне тогда задали этот вопрос и я на него тогда и ответил. Не знал, что нужно продублировать, прошу прощения

2023-12-14 12:20 UTC, ivankrn commented on src/test/java/ru/urfu/weatherforecastbot/bot/MessageHandlerImplTest.java
> +        String expected = forecastFormatter.formatForecasts(ForecastTimePeriod.WEEK, weekForecast);
Хорошо, понял

2023-12-14 12:20 UTC, merged