Задача 1
ivankrn/WeatherForecastBotOopCourse pull request #4
Opened 2023-11-16 17:26 UTC by ivankrn

2023-11-17 09:42 UTC, ivankrn commented
Ещё не готово (нужно исправить тесты в соответствии с изученным материалом на лекции)

2023-11-18 11:44 UTC, ivankrn commented
Теперь готово (поправил тесты)

2023-11-20 18:16 UTC, vpyzhyanov requested changes
В целом задача сделана очень хорошо. Молодцы! Но есть небольшие замечания.

Разве что ещё можно придираться к тому, что у вас куча ненужных интерфейсов, но это такой "стандарт" спринга, так что это допустимо. Но смысла в таких интерфейсах нет никакого (например GeocodingService, достаточно было одного класса).

Надо исправить замечания и показать мне задачу в действии.

2023-11-20 18:16 UTC, vpyzhyanov commented on src/test/java/ru/urfu/weatherforecastbot/bot/MessageHandlerImplTest.java
> +        проверка assertEquals должна упасть прежде, чем verify? (вопрос не только по этому конкретному тесту) */
Да, избыточна, assertEquals упадёт, если хотя бы один из этих методов не вызовется.

2023-11-20 18:16 UTC, vpyzhyanov commented on src/test/java/ru/urfu/weatherforecastbot/bot/MessageHandlerImplTest.java
> +    @DisplayName("При вводе нескольких последовательных команд, бот должен отвечать в том же порядке, в котором " +
тест не имеет смысла, т.к. ваш бот отвечает на сообщения **сразу же**.

2023-11-20 18:16 UTC, vpyzhyanov commented on src/test/java/ru/urfu/weatherforecastbot/service/WeatherForecastsDeserializerTest.java
> +        deserializer = new WeatherForecastsDeserializer();
нет необходимости создавать новый экземпляр перед **каждым** тестом

2023-11-20 18:16 UTC, vpyzhyanov commented on src/test/java/ru/urfu/weatherforecastbot/service/WeatherForecastsDeserializerTest.java
> +        assertThrows(IllegalArgumentException.class,
По хорошему тут надо ещё проверить текст сообщения в исключении. assertThrows возвращает объект исключения, из него можно легко достать сообщение и проверить на assertEquals

2023-11-20 18:16 UTC, vpyzhyanov commented on src/test/java/ru/urfu/weatherforecastbot/service/WeatherForecastsDeserializerTest.java
> +        assertThrows(IllegalArgumentException.class,
аналогично

2023-11-20 18:16 UTC, vpyzhyanov commented on src/test/java/ru/urfu/weatherforecastbot/util/WeatherForecastFormatterImplTest.java
> +        formatter = new WeatherForecastFormatterImpl();
нет необходимости создавать новый экземпляр перед **каждым** тестом. Можно его проинициализировать в поле

2023-11-20 18:16 UTC, vpyzhyanov commented on src/test/java/ru/urfu/weatherforecastbot/util/WeatherForecastFormatterImplTest.java
> +    // не уверен, что данный тест нужен (может ли в действительности сервис прислать прогноз, но при этом пустой?)
Этот тест тестирует форматтер, а не сервис прогноза погоды. По хорошему он должен учесть все ситуации

2023-11-21 05:46 UTC, ivankrn commented on src/main/java/ru/urfu/weatherforecastbot/service/WeatherForecastsDeserializer.java
> +        for (int i = 0; i < times.size(); i++) {
Не знаю, как в данном случае использовать foreach или стрим. API возвращает ответ в виде списка дат, списка температур, списка температур по ощущению, и для определения прогноза на какую-то дату нужно взять элементы из этих список на одной и той же позиции. Пример: если список дат выглядит так "times" : ["2023-11-21T00:00", "2023-11-21T01:00", ...], то для получения температуры в 00:00 нужно взять элементы из temperatures и feelsLikeTemperatures по индексу 0 (т.к. "2023-11-21T00:00" находится по индексу 0 в times)

2023-11-21 05:57 UTC, ivankrn commented on src/main/java/ru/urfu/weatherforecastbot/util/WeatherForecastFormatterImpl.java
> +public class WeatherForecastFormatterImpl implements WeatherForecastFormatter {
В третьей задаче нам потребуется отложенно отправлять сообщения, и скорее всего, сервису для отправки напоминаний так же для формирования сообщения пришлось бы запрашивать погоду и форматировать её, используя соответственно WeatherService и WeatherForecastFormatter, а так как несколько экземпляров WeatherForecastFormatter нам не потребуется в силу одинакового функционала, то решил оставить бином

2023-12-02 17:50 UTC, vpyzhyanov commented on src/main/java/ru/urfu/weatherforecastbot/config/BotInitializer.java
> +@Configuration
На всякий случай на будущее: если вы создаёте конфигурацию, то класс должен называться с использованием слово `Configuration`.

2023-12-02 18:17 UTC, vpyzhyanov commented on src/main/java/ru/urfu/weatherforecastbot/config/BotInitializer.java
> +            logger.error(e.getMessage());
Не случилось человекочитаемого исключения(

2023-12-02 18:42 UTC, vpyzhyanov requested changes
Как исправите последние замечания, можете мёрджить. Задача принята.

2023-12-02 18:42 UTC, vpyzhyanov commented on src/main/java/ru/urfu/weatherforecastbot/service/WeatherForecastsDeserializer.java
> +        for (int i = 0; i < times.size(); i++) {
разобрались. Пусть остаётся так

2023-12-02 18:42 UTC, vpyzhyanov commented on src/main/java/ru/urfu/weatherforecastbot/util/WeatherForecastFormatterImpl.java
> +public class WeatherForecastFormatterImpl implements WeatherForecastFormatter {
вроде написали, что оставили бином, но по факту теперь это не бин. И никакого комментария об этом нет. Это очень странно и непрозрачно!

Причина, которую вы описали - это прямой путь на тёмную сторону. Ведь класс, который отвечает за **форматирование**, не должен ничего запрашивать, он должен только форматировать то, что мы ему скажем.

2023-12-02 18:42 UTC, vpyzhyanov commented on src/main/java/ru/urfu/weatherforecastbot/util/WeatherForecastFormatterImpl.java
> +public class WeatherForecastFormatterImpl implements WeatherForecastFormatter {
1. Нет описания
2. Интерфейс не нужен и должен быть удалён. Теперь когда это не бин, вы не можете защититься "стандартами" спринга

2023-12-02 18:42 UTC, vpyzhyanov commented on src/main/java/ru/urfu/weatherforecastbot/util/WeatherForecastFormatterImpl.java
> +                    .filter(weatherForecast -> weatherForecast.dateTime().getHour() % 4 == 0)
что непонятного в слове "**константа**"?

2023-12-02 18:42 UTC, vpyzhyanov commented on src/test/java/ru/urfu/weatherforecastbot/bot/MessageHandlerImplTest.java
> +        проверка assertEquals должна упасть прежде, чем verify? (вопрос не только по этому конкретному тесту) */
в следующий раз задавайте вопросы с помощью комментариев в пулл реквесте, а не в коде. Код - не место для обсуждений

2023-12-02 18:42 UTC, vpyzhyanov commented on src/main/java/ru/urfu/weatherforecastbot/util/WeatherForecastFormatterImpl.java
> +                forecast.temperature() + "°C" +
`"°C"` тоже стоит вынести в константу. Так нужно поступить со всеми повторяющимися строками.

2023-12-03 07:01 UTC, ivankrn commented on src/main/java/ru/urfu/weatherforecastbot/util/WeatherForecastFormatterImpl.java
> +                    .filter(weatherForecast -> weatherForecast.dateTime().getHour() % 4 == 0)
Исправил

2023-12-04 07:44 UTC, merged